services:
  shlifscan:
    build:
      context: .
      args:
        TORCH_INDEX: https://download.pytorch.org/whl/cu121
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
